[package]
name = "egui-macroquad"
version = "0.9.0"
authors = ["Ilya Sheprut <optozorax@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
homepage = "https://github.com/optozorax/egui-macroquad"
repository = "https://github.com/optozorax/egui-macroquad"
description = "Bindings between egui and macroquad"
readme = "README.md"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[dependencies]
egui = "0.17.0"
# Temporal fix until macroquad updates its miniquad dep to alpha .46; After that, update
# egui-miniquad to 0.10.0
egui-miniquad = { git = "https://github.com/not-fl3/egui-miniquad/", rev = "8f493a03b98faf976374f8aea7d2448ffa4d115c" }
macroquad = { version = "0.3.15", default-features = false }

[dev-dependencies]
egui_demo_lib = { version = "0.17.0", default-features = false }

[profile.release]
opt-level = 2
